# Copyright (c) 2020 Ryan Cross
# SPDX-License-Identifier: MIT

# OLED Display
CONFIG_ZMK_DISPLAY=y

# Rotary Encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# RGB Underglow / Backlight
CONFIG_ZMK_RGB_UNDERGLOW=y

# Prevent RGB toggling from disabling OLED/external power
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
